name: Dimodo
description: Mobile commerce app by Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.6+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.0+2
  path_provider: ^1.6.8
  firebase_analytics: ^5.0.14
  path: 1.6.4
  smooth_page_indicator: ^0.1.4
  amplitude_flutter: ^2.0.0
  flutter_spinkit: "^4.1.2"
  sentry: ">=3.0.0 <4.0.0"
  webview_flutter: ^0.3.19+9
  provider: ^4.1.2
  algolia: ^0.1.7
  after_layout: 1.0.7+2
  json_annotation: ^3.0.1
  font_awesome_flutter: 8.5.0
  vector_math: 2.0.8
  timeago: 2.0.22
  share: 0.6.3+5
  validate: 1.7.0
  shared_preferences: ^0.5.7+2
  pull_to_refresh: 1.5.7
  localstorage: 3.0.1+4
  notification_permissions: 0.4.3
  flare_splash_screen: 3.0.0
  rate_my_app: ^0.6.1+2
  page_indicator: 0.3.0
  extended_image: ^0.7.4
  fluttertoast: 3.1.3
  url_launcher: 5.4.1
  connectivity: 0.4.8
  random_string: 1.1.0
  cached_network_image: ^2.1.0+1
  flutter_swiper: 1.1.6
  flutter_facebook_login: 3.0.0
  flutter_localizations:
    sdk: flutter
  google_sign_in: 4.1.0
  google_fonts: ^0.2.0
  flutter_mailer: ^0.4.2
  flutter_svg: ^0.17.4
  uuid: 2.0.4
  uni_links: 0.2.0
dev_dependencies:
  flutter_launcher_icons: 0.7.4
  json_serializable: ^3.2.5
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter

# Run this script to generate the app icon: flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/common/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/account/
    - assets/icons/cart/
    - assets/icons/search/
    - assets/icons/address/
    - assets/icons/
    - assets/icons/auth/
    - assets/icons/home/
    - assets/icons/setting/
    - assets/icons/payment/
    - assets/icons/product_detail/
    - assets/icons/order/
    - assets/files/
    - assets/images/onboarding/
    - assets/images/
    - assets/images/country/
    - assets/fonts/BeVietnam/
  fonts:
    - family: BeVietnam
      fonts:
        - asset: assets/fonts/BeVietnam/BeVietnam-Regular.ttf
        - asset: assets/fonts/BeVietnam/BeVietnam-Italic.ttf
        - asset: assets/fonts/BeVietnam/BeVietnam-Bold.ttf
        - asset: assets/fonts/BeVietnam/BeVietnam-SemiBold.ttf
        - asset: assets/fonts/BeVietnam/BeVietnam-Thin.ttf
        - asset: assets/fonts/BeVietnam/BeVietnam-ThinItalic.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
