INSERT INTO product (sid, sname, name, volume, description, sale_price, price, purchase_count, average_rating, thumbnail, is_discontinued, brand_id, brand_img, sdescription, category_id)
SELECT
	sid,
	sname,
	name,
	volume,
	description,
	sale_price,
	price,
	review_count,
	average_rating,
	thumbnail,
	is_discontinued,
	brand_id,
	brand_img,
	sdescription,
	category_id
FROM
	cosmetics_products_clone