// Generated by https://quicktype.io
import 'package:Dimodo/models/second_category.dart';
import 'package:json_annotation/json_annotation.dart';

part 'category.g.dart';

@JsonSerializable(fieldRename: FieldRename.snake, explicitToJson: true)
class Category {
  String koName;
  String enName;
  String name;
  List<Category> subCategories;
  List<String> synonyms;
  String image;
  int id;
  int level;
  double grandTotalCount;

  Category(
      {this.koName,
      this.enName,
      this.name,
      this.subCategories,
      this.synonyms,
      this.grandTotalCount,
      this.image,
      this.id,
      this.level});
  factory Category.fromJson(Map<String, dynamic> json) =>
      _$CategoryFromJson(json);
  Map<String, dynamic> toJson() => _$CategoryToJson(this);
}
