// Generated by https://quicktype.io
import 'package:Dimodo/models/second_category.dart';
import 'package:json_annotation/json_annotation.dart';

part 'category.g.dart';

@JsonSerializable(fieldRename: FieldRename.snake)
class Category {
  String firstCategoryKoName;
  String firstCategoryEnName;
  String firstCategoryName;
  List<SecondCategory> secondCategories;
  String firstCategoryImage;
  int idFirstCategory;
  bool firstIsNew;

  Category({
    this.firstCategoryKoName,
    this.firstCategoryEnName,
    this.firstCategoryName,
    this.secondCategories,
    this.firstCategoryImage,
    this.idFirstCategory,
    this.firstIsNew,
  });
  factory Category.fromJson(Map<String, dynamic> json) =>
      _$CategoryFromJson(json);
  Map<String, dynamic> toJson() => _$CategoryToJson(this);
}
