// Generated by https://quicktype.io
import 'package:Dimodo/models/product/product.dart';
import 'package:Dimodo/models/second_category.dart';
import 'package:Dimodo/models/user/user.dart';
import 'package:json_annotation/json_annotation.dart';

part 'product_request.g.dart';

@JsonSerializable(fieldRename: FieldRename.snake, explicitToJson: true)
class ProductRequest {
  bool isUploaded;
  bool sentNotificaiton;
  Product product;
  String productName;
  String categoryName;
  String brandName;
  User user;
  int id;

  ProductRequest(
      {this.isUploaded,
      this.sentNotificaiton,
      this.product,
      this.productName,
      this.brandName,
      this.categoryName,
      this.id});

  factory ProductRequest.fromJson(Map<String, dynamic> json) =>
      _$ProductRequestFromJson(json);
  Map<String, dynamic> toJson() => _$ProductRequestToJson(this);
}
