// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'third_category.g.dart';

@JsonSerializable(fieldRename: FieldRename.snake)
class ThirdCategory {
  bool thirdIsNew;
  String thirdCategoryKoName;
  String thirdCategoryEnName;
  String thirdCategoryName;
  int thirdCategoryId;

  ThirdCategory({
    this.thirdIsNew,
    this.thirdCategoryKoName,
    this.thirdCategoryEnName,
    this.thirdCategoryName,
    this.thirdCategoryId,
  });
  factory ThirdCategory.fromJson(Map<String, dynamic> json) =>
      _$ThirdCategoryFromJson(json);
  Map<String, dynamic> toJson() => _$ThirdCategoryToJson(this);
}
